PersonalPorfolio/Models/ApplicationUser.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace PersonalPortfolio.Models
{
    public class ApplicationUser : IdentityUser
    {
    }
}

PersonalPorfolio/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalPortfolio.ViewModels
{
    public class LoginViewModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

PersonalPorfolio/ViewModels/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace PersonalPortfolio.ViewModels
{
    public class RegisterViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

PersonalPorfolio/Controllers/BlogController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using PersonalPortfolio.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using System.Collections.Generic;
using System;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace PersonalPortfolio.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public BlogController(UserManager<ApplicationUser> userManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        [HttpPost]
        public async Task<IActionResult> DeleteComment(int id)
        {
            var associatedComment = _db.Comments.Include(c => c.AssociatedBlog).FirstOrDefault( c => c.CommentKey == id);
            var blogId = associatedComment.AssociatedBlog.BlogKey;
            if (associatedComment != null)
            {
                _db.Comments.Remove(associatedComment);
                _db.SaveChanges();                
            }
            return PartialView("Comment",_db.Comments.Include(c => c.AssociatedBlog).Where(c => c.AssociatedBlog.BlogKey == blogId).ToList());
        }
       

        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            return View(_db.Blogs.Include(b => b.Comments).Where(x => x.User.Id == currentUser.Id));
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Blog blog)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            blog.User = currentUser;
            _db.Blogs.Add(blog);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreateComment(Comment comment)
        {
            if (!string.IsNullOrWhiteSpace(comment.CommentText) && comment.BlogKey != default(int)) {
                var blog = _db.Blogs.Find(comment.BlogKey);
                comment.ReplyDtm = DateTime.Now;
                comment.AssociatedBlog = blog;
                _db.Comments.Add(comment);

                await _db.SaveChangesAsync();
            }
            return PartialView("Comment",_db.Comments.Where(c => c.AssociatedBlog.BlogKey == comment.BlogKey).ToList());
        }

        

        public IActionResult HelloAjax()
        {
            return Content("Hello from the controller!", "text/plain");
        }
        public IActionResult Blog()
        {
            return View();
        }
      
    }
}

PersonalPorfolio/Views/ApplicationUsers/Index.cshtml
@model IEnumerable<PersonalPortfolio.Models.ApplicationUser>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Security.Claims

<h2>Authentication with Identity</h2>
<hr />
@if (User.Identity.IsAuthenticated)
{
    <p>Hello @User.Identity.Name!</p>
    @using (Html.BeginForm("LogOff", "ApplicationUsers"))
    {
        <input type="submit" class="btn btn-default" value="Log out" />
    }

   <h2>@Html.ActionLink("Blogs", "Blog", "Blog")</h2> 
}
else
{
    <p>@Html.ActionLink("Register", "Register")</p>
    <p>@Html.ActionLink("Log in", "Login")</p>
}

PersonalPorfolio/Views/ApplicationUsers/Login.cshtml
@{
    ViewData["Title"] = "Log In";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using PersonalPortfolio.ViewModels

@model LoginViewModel
<h2>Log in with your account</h2>
<hr />
@using (Html.BeginForm())
{
    @Html.LabelFor(m => m.Email)
    @Html.TextBoxFor(m => m.Email)

    @Html.LabelFor(m => m.Password)
    @Html.PasswordFor(m => m.Password)

    <input type="submit" value="Log in" class="btn btn-default" />
}

PersonalPorfolio/Views/ApplicationUsers/Register.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using PersonalPortfolio.ViewModels

@model RegisterViewModel

<h2>Register a new user</h2>
<hr />
@using (Html.BeginForm("Register", "ApplicationUsers", FormMethod.Post))
{
    @Html.LabelFor(user => user.Email)
    @Html.TextBoxFor(user => user.Email)

    @Html.LabelFor(user => user.Password)
    @Html.PasswordFor(user => user.Password)

    @Html.LabelFor(user => user.ConfirmPassword)
    @Html.PasswordFor(user => user.ConfirmPassword)

    <input type="submit" value="Register" />
}